version: '3'

services:
  db:
    image: mysql:5.7
    command:
      - --lower_case_table_names=1
    ports:
      - "13306:3306"
    restart: always
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: HELLO-REST
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: hellorest
      MYSQL_PASSWORD: 1111
      TZ: Asia/Seoul